### ISSUE TITLE
add instruction to home page on how to get access to this community edition

### ISSUE THREAD

**Issue by DinisCruz** [continuumsecurity/IriusRisk#3]
on https://github.com/continuumsecurity/IriusRisk

**Comment by iriusrisk** [comment]
We still have a handful of issues to address before launching community - so although it's available, it's not advertised or promoted yet until official launch.

**Comment by stephendv1** [comment]
Getting started guide, including instructions and more detailed docs added to README.md

**Comment by DinisCruz** [comment]
nice  :)

![image](https://cloud.githubusercontent.com/assets/656739/20156027/7eb05da0-a6c6-11e6-8334-ee7e718f410a.png)
