### ISSUE TITLE
Improper classification of POODLE: CWE-209

### ISSUE THREAD

**Issue by fadeevab** [continuumsecurity/IriusRisk#6]
IriusRisk has CWE-209-POODLE which seems improper classification.

POODLE attack seems not to be CWE-209: Information Exposure Through an Error Message (http://cwe.mitre.org/data/definitions/209.html).

It looks like to be more likely **CWE-327: Use of a Broken or Risky Cryptographic Algorithm**.

Thank you for a feedback.

**Comment by v3rn3** [comment]
@fadeevab, sorry for the late reply. You are right, reference should be **CWE-327** and we’ll update it asap.
Best regards and thank you for reporting us this issue.

**Comment by fadeevab** [comment]
Great, thank you!
