### ISSUE TITLE
Community edition registration date passed but no release?

### ISSUE THREAD

**Issue by huornlmj** [continuumsecurity/IriusRisk#8]
When will the community edition of IriusRisk be available?

**Comment by stephendv1** [comment]
The new version will be released on 12th September during AppSec USA

**Comment by huornlmj** [comment]
Does this mean registration is open now or will 12th September be the new date that registrations will re-open?

**Comment by stephendv1** [comment]
It will be open on the 12th.

**Comment by stephendv1** [comment]
New community has been released!
